### Linear Regression - Tuning

In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression,Lasso,Ridge

In [34]:
car_data = pd.read_csv('data_set/car-mpg.csv')
car_data.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [35]:
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64
 2   disp      398 non-null    float64
 3   hp        398 non-null    str
 4   wt        398 non-null    int64
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64
 7   origin    398 non-null    int64
 8   car_type  398 non-null    int64
 9   car_name  398 non-null    str
dtypes: float64(3), int64(5), str(2)
memory usage: 38.4 KB

In [36]:
car_data.describe()

,mpg,cyl,disp,wt,acc,yr,origin,car_type
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864,0.530151
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055,0.499718
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000,0.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000,0.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000,1.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000,1.000000

### Data Cleaning

In [37]:
car_data.isnull().sum()

mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car_type    0
car_name    0
dtype: int64

In [38]:
car_data

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,1,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,1,chevy s-10

In [39]:
car_data = car_data.drop(['car_name'], axis = 1)
car_data['origin'] = car_data['origin'].replace({1: 'america', 2: 'europe', 3: 'asia'})
car_data = pd.get_dummies(car_data,columns = ['origin'])

In [40]:
car_data = car_data.replace('?', np.nan)
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cyl             398 non-null    int64
 2   disp            398 non-null    float64
 3   hp              392 non-null    str
 4   wt              398 non-null    int64
 5   acc             398 non-null    float64
 6   yr              398 non-null    int64
 7   car_type        398 non-null    int64
 8   origin_america  398 non-null    bool
 9   origin_asia     398 non-null    bool
 10  origin_europe   398 non-null    bool
dtypes: bool(3), float64(3), int64(4), str(1)
memory usage: 27.1 KB

In [41]:
car_data['hp'] = pd.to_numeric(car_data['hp'], errors='coerce')
car_data.isnull().sum()

mpg               0
cyl               0
disp              0
hp                6
wt                0
acc               0
yr                0
car_type          0
origin_america    0
origin_asia       0
origin_europe     0
dtype: int64

In [42]:
car_data = car_data.apply(lambda x: x.fillna(x.median()), axis = 0)
car_data.isnull().sum()

mpg               0
cyl               0
disp              0
hp                0
wt                0
acc               0
yr                0
car_type          0
origin_america    0
origin_asia       0
origin_europe     0
dtype: int64

### Model Building

In [43]:
x = car_data.drop(['mpg'],axis = 1)
y = car_data[['mpg']]

In [45]:
#Scaling the data

X_s = preprocessing.scale(x)
X_s = pd.DataFrame(X_s, columns = x.columns) #converting scaled data into dataframe

y_s = preprocessing.scale(y)
y_s = pd.DataFrame(y_s, columns = y.columns) #ideally train, test data should be in columns

In [46]:
x_train,x_test,y_train,y_test = train_test_split(X_s,y_s,train_size=0.2,random_state=42)

In [47]:
x_train

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
212,1.498191,1.503514,1.982890,1.666604,-1.259190,-0.002721,-1.062235,0.773559,-0.497643,-0.461968
295,-0.856321,-0.916334,-0.636655,-1.247875,-0.424109,0.809631,0.941412,0.773559,-0.497643,-0.461968
362,0.320935,-0.455410,0.411163,-0.047796,-0.641956,1.351199,-1.062235,-1.292726,2.009471,-0.461968
251,1.498191,1.042591,0.908877,0.708905,-1.005035,0.538847,-1.062235,0.773559,-0.497643,-0.461968
388,-0.856321,-0.359385,-0.322309,-0.455705,-0.387801,1.621983,0.941412,0.773559,-0.497643,-0.461968
...,...,...,...,...,...,...,...,...,...,...
71,-1.444949,-1.185206,-0.191332,-0.757202,-0.750880,-1.085858,0.941412,-1.292726,2.009471,-0.461968
106,1.498191,1.503514,1.982890,1.807303,-1.113959,-0.815074,-1.062235,0.773559,-0.497643,-0.461968
270,-0.856321,-0.570641,-0.243723,-0.538469,-0.278877,0.538847,0.941412,-1.292726,2.009471,-0.461968
348,-0.856321,-1.002757,-1.108173,-1.088259,0.628820,1.351199,0.941412,-1.292726,2.009471,-0.461968
102,-0.856321,-0.925936,-1.527300,-1.206493,1.972212,-0.815074,0.941412,-1.292726,-0.497643,2.164651

In [48]:
y_train

          mpg
212 -0.898595
295  1.561002
362  0.087806
251 -0.424610
388  0.318393
..        ...
71  -0.578335
106 -1.475063
270 -0.309316
348  1.817210
102  0.318393

[79 rows x 1 columns]

### 1. Linear Regression Model

In [52]:
linear_model = LinearRegression()
linear_model.fit(x_train,y_train)
y_pred = linear_model.predict(x_test)

In [53]:
y_pred

array([[ 1.03474377],
       [ 0.93223536],
       [-0.52800034],
       [-0.88489558],
       [-1.38215977],
       [ 0.27767735],
       [ 0.70082659],
       [-2.06591213],
       [-0.68232268],
       [-0.37994012],
       [-1.59087296],
       [ 1.42565829],
       [ 0.40566444],
       [-1.22558713],
       [ 0.24487841],
       [-2.23230569],
       [ 0.94707945],
       [-0.01033106],
       [-1.1481547 ],
       [ 1.41249155],
       [ 0.37874639],
       [-0.73413792],
       [ 0.31790578],
       [ 0.83842046],
       [-1.0500474 ],
       [ 1.70419757],
       [ 0.59509908],
       [ 0.32903056],
       [-0.51409283],
       [-1.95507303],
       [ 0.78291647],
       [ 1.72393004],
       [-0.47465371],
       [ 0.11662504],
       [ 1.20549798],
       [-1.79690656],
       [-0.23267548],
       [-0.30426605],
       [-1.37596212],
       [ 0.75298093],
       [ 0.13662559],
       [ 0.84062055],
       [-0.07798912],
       [-2.24638665],
       [-0.05369979],
       [ 1.18287679],
       [ 0.76979865],
       [ 0.38018636],
       [ 0.20332689],
       [ 0.90319964],
       [ 0.06398211],
       [ 1.14373129],
       [ 0.97414782],
       [-1.81495492],
       [ 0.33285445],
       [-1.86859531],
       [-0.61285128],
       [ 0.58843347],
       [ 0.08930651],
       [-0.57222935],
       [-1.12009713],
       [ 0.93943764],
       [ 0.23471723],
       [-0.0045216 ],
       [-0.49982877],
       [ 0.0596694 ],
       [ 0.35379221],
       [ 1.32242391],
       [ 0.77458869],
       [-1.28251378],
       [ 1.21201483],
       [-1.29852379],
       [-1.98955691],
       [-0.81480571],
       [ 0.26288882],
       [-0.09040205],
       [-0.64057427],
       [ 0.90551736],
       [ 1.11430219],
       [-0.43687081],
       [-1.09121008],
       [ 0.07016972],
       [ 1.37255073],
       [ 1.19110832],
       [ 0.4552221 ],
       [-1.71874841],
       [ 1.09597687],
       [ 1.07751197],
       [ 0.24174172],
       [-2.13792959],
       [-1.2704179 ],
       [ 0.6005216 ],
       [ 0.733831  ],
       [ 1.43349928],
       [-0.32177298],
       [ 1.37097226],
       [ 0.9798391 ],
       [-0.27137655],
       [ 0.49515988],
       [-1.36349098],
       [ 1.2087054 ],
       [ 0.14482751],
       [-0.70208364],
       [-1.06853299],
       [-0.76396493],
       [-2.04816062],
       [ 0.8064409 ],
       [-1.62322043],
       [ 1.48287786],
       [ 1.32615484],
       [ 0.75983758],
       [ 0.75563336],
       [-0.23497351],
       [ 1.42430372],
       [ 0.6171992 ],
       [ 0.07514626],
       [ 0.64619781],
       [-0.32977901],
       [ 1.36160071],
       [-0.24184206],
       [-1.32147259],
       [ 0.2581754 ],
       [-0.51620513],
       [-0.20615108],
       [-0.58000483],
       [ 0.13976536],
       [ 1.30989879],
       [ 0.64478974],
       [ 1.33595074],
       [ 0.81003538],
       [ 1.25888623],
       [ 0.66048979],
       [ 1.13624255],
       [-0.5160247 ],
       [ 0.36466759],
       [-0.59121049],
       [-0.44128779],
       [ 1.50848744],
       [ 0.94541495],
       [ 1.11686847],
       [-0.9543784 ],
       [-1.52137735],
       [-0.65593482],
       [-0.40637506],
       [-0.33323224],
       [ 0.90646621],
       [ 0.65854917],
       [ 0.18760431],
       [ 0.6128019 ],
       [ 0.19962766],
       [-2.10635225],
       [-0.56556244],
       [ 0.77447798],
       [ 0.23802424],
       [-1.29693466],
       [ 1.10075781],
       [-1.9437677 ],
       [ 0.12571332],
       [-0.66640572],
       [ 0.93132996],
       [ 0.56915795],
       [-0.66459235],
       [ 0.57385226],
       [-0.2709887 ],
       [-1.05394975],
       [-0.7482495 ],
       [-0.94538474],
       [ 0.87266687],
       [-0.17597103],
       [-1.51572745],
       [-1.68627504],
       [-0.58105569],
       [-1.21100275],
       [ 0.7231151 ],
       [ 1.03534987],
       [-0.70869526],
       [-0.59381035],
       [-1.69565877],
       [ 0.2239013 ],
       [-0.99396469],
       [ 0.95869873],
       [ 0.21979978],
       [-2.05325256],
       [-0.50402709],
       [ 0.71137438],
       [ 1.35624454],
       [-0.1613359 ],
       [-0.22984717],
       [-0.54529084],
       [ 0.56002365],
       [ 1.26228412],
       [-0.97342037],
       [ 1.09736873],
       [ 1.28497754],
       [ 0.47954653],
       [-0.90871757],
       [-0.41634939],
       [ 1.00338521],
       [ 0.94508404],
       [ 1.04157153],
       [ 0.41456019],
       [ 0.16149439],
       [ 0.05140133],
       [ 0.67150199],
       [-1.62737888],
       [-1.26539163],
       [ 1.39189148],
       [ 0.63134929],
       [ 0.94883797],
       [ 0.27020582],
       [ 0.26342841],
       [ 0.66216245],
       [-0.03383682],
       [ 1.06676705],
       [-0.09833659],
       [ 0.56252988],
       [ 1.20518984],
       [-0.34632842],
       [ 0.48105005],
       [-0.4827549 ],
       [ 1.40218357],
       [-1.16707913],
       [-0.60247142],
       [-0.77632515],
       [ 1.20902779],
       [ 0.78327126],
       [-1.09595044],
       [ 0.82160944],
       [-1.25734174],
       [-1.07694675],
       [ 1.0566817 ],
       [-1.99339172],
       [ 0.06101903],
       [ 0.55939175],
       [-0.9459657 ],
       [ 1.25266437],
       [ 0.94511586],
       [ 0.52222646],
       [ 0.98943741],
       [-0.43672589],
       [-1.46905281],
       [ 0.98110229],
       [ 0.16528234],
       [ 0.31567642],
       [ 1.31884013],
       [-0.45093372],
       [ 0.95233159],
       [ 0.44298897],
       [-1.06500027],
       [ 1.45270376],
       [ 0.3396439 ],
       [-0.9324573 ],
       [-2.34620137],
       [ 0.18056896],
       [-1.42279956],
       [ 0.78037581],
       [-1.40833482],
       [ 0.64487757],
       [ 0.95653758],
       [-1.48766471],
       [-1.34891061],
       [-1.02873635],
       [-2.21792785],
       [ 0.2880039 ],
       [ 1.01536783],
       [ 1.37024487],
       [ 0.33926367],
       [-0.71883848],
       [-2.26919725],
       [ 0.63019482],
       [ 1.08678652],
       [ 0.47082605],
       [ 1.57203331],
       [ 0.29655585],
       [-1.47006515],
       [ 1.68942375],
       [ 0.43929615],
       [-0.02143989],
       [ 0.301239  ],
       [-1.05283686],
       [-0.42930824],
       [ 1.01318639],
       [-0.56795894],
       [-0.54531951],
       [ 0.77711873],
       [-0.95103145],
       [ 0.09542605],
       [-0.80738945],
       [-0.75600264],
       [ 0.23358062],
       [-0.99462973],
       [ 0.23378793],
       [ 0.48414168],
       [-0.6351414 ],
       [ 1.2998531 ],
       [-2.04440311],
       [ 1.15273412],
       [-1.04756856],
       [-0.61227784],
       [-0.45671764],
       [-0.98650477],
       [ 0.90998505],
       [-1.44023109],
       [-1.57809689],
       [-0.96048523],
       [-0.75123675],
       [-2.18172447],
       [-1.40341845],
       [ 0.04516665],
       [-0.13891078],
       [-1.60893225],
       [-1.53650689],
       [-0.07193348],
       [ 1.13843246],
       [ 0.88002528],
       [ 0.9153568 ],
       [ 0.88277443],
       [ 0.31781424],
       [ 0.19030441]])

In [56]:
for idx, col_name in enumerate(x_train.columns):
    print('The coefficient for {} is {}'.format(col_name, linear_model.coef_[0][idx]))
    
intercept = linear_model.intercept_[0]
print('The intercept is {}'.format(intercept))

The coefficient for cyl is 0.29499692534693933
The coefficient for disp is -0.033920910221457046
The coefficient for hp is -0.1759867299578932
The coefficient for wt is -0.5963461579592573
The coefficient for acc is -0.00532969514369564
The coefficient for yr is 0.3512488479886575
The coefficient for car_type is 0.3156654886699788
The coefficient for origin_america is -0.03318875832539398
The coefficient for origin_asia is -0.04477047791945334
The coefficient for origin_europe is 0.08909338561503707
The intercept is -0.015748517594096796

### 2. Ridge Model

In [60]:
#alpha factor here is lambda (penalty term) which helps to reduce the magnitude of coeff

ridge_model = Ridge(alpha = 0.3)
ridge_model.fit(x_train, y_train)

for idx, col_name in enumerate(x_train.columns):
    print('The coefficient for {} is {}'.format(col_name, ridge_model.coef_[idx]))
intercept_ridge = ridge_model.intercept_[0]
print('The intercept is {}'.format(intercept_ridge))

The coefficient for cyl is 0.26745175937815313
The coefficient for disp is -0.03140532364418652
The coefficient for hp is -0.17687530267967977
The coefficient for wt is -0.5827203686188552
The coefficient for acc is -0.010203616643552037
The coefficient for yr is 0.34906586450675414
The coefficient for car_type is 0.30311324819453855
The coefficient for origin_america is -0.03401725359632324
The coefficient for origin_asia is -0.04400878445115745
The coefficient for origin_europe is 0.08934855125960772
The intercept is -0.016481193082953496

### 3. Lasso Model

In [62]:
#alpha factor here is lambda (penalty term) which helps to reduce the magnitude of coeff

lasso_model = Lasso(alpha = 0.1)
lasso_model.fit(x_train, y_train)

for idx, col_name in enumerate(x_train.columns):
    print('The coefficient for {} is {}'.format(col_name, lasso_model.coef_[idx]))
intercept_lasso = lasso_model.intercept_[0]
print('The intercept is {}'.format(intercept_lasso))

The coefficient for cyl is -0.0
The coefficient for disp is -0.0
The coefficient for hp is -0.052070993659097876
The coefficient for wt is -0.4934417253252299
The coefficient for acc is 0.0
The coefficient for yr is 0.25016950602515264
The coefficient for car_type is 0.18950960195259767
The coefficient for origin_america is -0.0
The coefficient for origin_asia is -0.0
The coefficient for origin_europe is 0.02021004702771472
The intercept is -0.019069630135386484

### Score Comparision
Model score - r^2 or coeff of determinant

r^2 = 1-(RSS/TSS) = Regression error/TSS

In [65]:

# Linear Model
print('----Linear Regression----')
print(linear_model.score(x_train, y_train))
print(linear_model.score(x_test, y_test))

#Ridge
print('----Ridge Regression----')
print(ridge_model.score(x_train, y_train))
print(ridge_model.score(x_test, y_test))

print('----Lasso Regression----')
#Lasso
print(lasso_model.score(x_train, y_train))
print(lasso_model.score(x_test, y_test))

----Linear Regression----
0.8485579984789502
0.8031526483234158
----Ridge Regression----
0.8484810486327186
0.8030707814796705
----Lasso Regression----
0.8132245383124739
0.8074894059167002